### ISSUE TITLE
Ignore Folder

### ISSUE THREAD

**Issue by TreeHD** [nils-soderman/vscode-sitemap-generator#2]
Hello

How could i ignore a whole folder?

I've trying add 
```
 "Exclude": [
  "/archive"
]
```
But it's not working

**Comment by nils-soderman** [comment]
Hi, the exclude is expecting a glob pattern.

So to exclude all content from archive you'd write _(assuming archive is located directly under the root)_:
`"archive/*"`

If archive is one or multiple subfolders, you could exclude all folders named _archive_ using:
`"**/archive/*"`

I should probably add some info regarding this to the Readme.md. Thank you for bringing it up and let me know if you run into any other issues!
